# Generated by Django 3.0.7 on 2020-06-13 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('youtube_title', models.CharField(max_length=150)),
                ('front_text', models.TextField(max_length=500)),
                ('back_text', models.TextField(max_length=500)),
                ('front_img', models.ImageField(upload_to='')),
                ('back_img', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=20)),
                ('finished_count', models.PositiveSmallIntegerField()),
                ('youtube_timestamp', models.TimeField()),
                ('due_time', models.DateTimeField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Deck')),
            ],
        ),
    ]
