# Generated by Django 3.0.7 on 2020-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(choices=[('N', 'NEW'), ('R', 'REVIEW'), ('L', 'LEARNING'), ('F', 'FINISHED')], default='N', max_length=20),
        ),
    ]
